const UserValidationRule = {
	EMAIL_MINIMUM_LENGTH: 1,
	FIELD_MINIMUM_LENGTH: 1,
	FIRSTNAME_MAX_LENGTH: 16,
	FIRSTNAME_MINIMUM_LENGTH: 2,
	LASTNAME_MAX_LENGTH: 25,
	LASTNAME_MINIMUM_LENGTH: 3,
	PASSWORD_MINIMUM_LENGTH: 8,
} as const;

export { UserValidationRule };
