const UserValidationRule = {
	EMAIL_DOMAIN_PART_MAXIMUM_LENGTH: 35,
	EMAIL_LOCAL_PART_MAXIMUM_LENGTH: 35,
	EMAIL_MINIMUM_LENGTH: 1,
	FIELD_MINIMUM_LENGTH: 1,
	FIRST_NAME_MAXIMUM_LENGTH: 35,
	FIRST_NAME_MINIMUM_LENGTH: 2,
	LAST_NAME_MAXIMUM_LENGTH: 35,
	LAST_NAME_MINIMUM_LENGTH: 2,
	PASSWORD_MAXIMUM_LENGTH: 26,
	PASSWORD_MINIMUM_LENGTH: 8,
} as const;

export { UserValidationRule };
