const UserValidationRule = {
	CONFIRM_PASSWORD_MINIMUM_LENGTH: 8,
	EMAIL_MINIMUM_LENGTH: 1,
	FIRSTNAME_MINIMUM_LENGTH: 2,
	LASTNAME_MINIMUM_LENGTH: 3,
	PASSWORD_MINIMUM_LENGTH: 8,
} as const;

export { UserValidationRule };
