name: Continuous Delivery

env:
  AWS_REGION: eu-central-1
  EBS_APPLICATION_NAME: trackmates
  EBS_ENVIRONMENT_NAME: development

on:
  push:
    branches:
      - main
    paths:
      - apps/**/*.*
      - packages/**/*.*
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3

  deploy:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Prepare deployment package
        run: |
          zip -r build.zip . -x .github

      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          application_name: ${{ env.EBS_APPLICATION_NAME }}
          environment_name: ${{ env.EBS_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          deployment_package: ./build.zip
